language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      env:
        - R_CODECOV=true
        - MAKEFLAGS="-j 2"
      addons:
        apt:
          packages:
            - libv8-dev
            - libssh2-1-dev
    - os: osx
      osx_image: xcode7.2
      latex: false
      env:
        - R_CODECOV=true
        - MAKEFLAGS="-j 2"

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
